import type {
  FaqEntry,
  FeedItem,
  FollowedUser,
  LibraryHours,
  Resource,
  StudySpace,
} from '@/types'

/** Spine colours for generated covers — the university sky/navy plus accents. */
const C = {
  sky: '#0369A1',
  navy: '#0C2342',
  steel: '#3D5A80',
  clay: '#8C3A2B',
  indigo: '#2E3A76',
  teal: '#0F5B63',
  plum: '#5B2C57',
}

export const SUBJECT_AREAS = [
  'Medicine & Health Sciences',
  'Law',
  'Engineering',
  'Education',
  'Agriculture',
  'Natural Sciences',
  'Social Sciences',
  'Arts & Humanities',
  'Management Sciences',
  'Environmental Sciences',
]

export const RESOURCES: Resource[] = [
  {
    id: 'r-001',
    biblionumber: '104233',
    title: 'Principles of Tropical Medicine and Public Health',
    authors: ['A. O. Danjuma', 'Grace Pam'],
    type: 'book',
    subjects: ['Medicine & Health Sciences', 'Public Health'],
    year: 2021,
    publisher: 'Jos University Press',
    isbn: '9789785432101',
    language: 'English',
    callNumber: 'RA441.5 .D36 2021',
    location: 'Main Library — Level 2, Health Sciences',
    copiesTotal: 6,
    copiesAvailable: 2,
    abstract:
      'A clinical and community-facing survey of tropical disease burden, control programmes and health-system delivery in West Africa, with case studies drawn from Plateau State.',
    coverColor: C.sky,
    accessCount: 412,
  },
  {
    id: 'r-002',
    biblionumber: '104987',
    title: 'Nigerian Constitutional Law: Cases and Commentary',
    authors: ['Emeka Nwachukwu'],
    type: 'book',
    subjects: ['Law', 'Constitutional Law'],
    year: 2022,
    publisher: 'Spectrum Books',
    isbn: '9789780292201',
    language: 'English',
    callNumber: 'KTA2070 .N93 2022',
    location: 'Law Library — Level 1',
    copiesTotal: 8,
    copiesAvailable: 0,
    abstract:
      'Annotated decisions of the Supreme Court on federalism, fundamental rights and the separation of powers under the 1999 Constitution as amended.',
    coverColor: C.indigo,
    accessCount: 388,
  },
  {
    id: 'r-003',
    title: 'Journal of Applied Sciences and Environmental Management',
    authors: ['Editorial Board'],
    type: 'journal',
    subjects: ['Environmental Sciences', 'Natural Sciences'],
    year: 2024,
    language: 'English',
    url: 'https://ajol.info/index.php/jasem',
    abstract:
      'Peer-reviewed African research on environmental chemistry, waste management, and applied ecology. Full run available through the library e-journal gateway.',
    coverColor: C.teal,
    accessCount: 526,
  },
  {
    id: 'r-004',
    title: 'Tin Mining and Land Degradation on the Jos Plateau',
    authors: ['Rifkatu Bulus'],
    type: 'thesis',
    subjects: ['Environmental Sciences', 'Geography'],
    year: 2023,
    language: 'English',
    url: '/repository/theses/2023/bulus-tin-mining',
    repository: true,
    abstract:
      'Doctoral thesis mapping six decades of mine-pond formation, soil loss and reclamation attempts across the Plateau, using remote sensing and field survey.',
    coverColor: C.clay,
    accessCount: 297,
  },
  {
    id: 'r-005',
    biblionumber: '103771',
    title: 'Structural Analysis for Civil Engineers',
    authors: ['Ibrahim Sule', 'Peter Oyelaran'],
    type: 'book',
    subjects: ['Engineering'],
    year: 2020,
    publisher: 'Ahmadu Bello University Press',
    isbn: '9789781256789',
    language: 'English',
    callNumber: 'TA645 .S85 2020',
    location: 'Main Library — Level 3, Engineering',
    copiesTotal: 5,
    copiesAvailable: 3,
    abstract:
      'Determinate and indeterminate structures, influence lines, and matrix methods, worked with SI units and Nigerian design-code examples.',
    coverColor: C.steel,
    accessCount: 244,
  },
  {
    id: 'r-006',
    title: 'AJOL: African Journals OnLine',
    authors: ['Consortium'],
    type: 'journal',
    subjects: ['Social Sciences', 'Natural Sciences', 'Arts & Humanities'],
    year: 2025,
    language: 'Multiple',
    url: 'https://www.ajol.info',
    abstract:
      'The largest collection of peer-reviewed African-published scholarly journals. Access is authenticated through the library proxy.',
    coverColor: C.plum,
    accessCount: 731,
  },
  {
    id: 'r-007',
    biblionumber: '105112',
    title: 'Curriculum Studies and Instructional Design in Nigeria',
    authors: ['Ladi Machunga'],
    type: 'book',
    subjects: ['Education'],
    year: 2019,
    publisher: 'University of Jos Press',
    isbn: '9789785110099',
    language: 'English',
    callNumber: 'LB1570 .M33 2019',
    location: 'Education Wing — Level 1',
    copiesTotal: 10,
    copiesAvailable: 7,
    abstract:
      'A practitioner text on curriculum theory, syllabus construction and classroom assessment for teacher-education programmes.',
    coverColor: C.navy,
    accessCount: 189,
  },
  {
    id: 'r-008',
    title: 'Soil Fertility Management for Smallholder Maize Systems',
    authors: ['Comfort Adeyemi', 'John Gyang'],
    type: 'article',
    subjects: ['Agriculture'],
    year: 2024,
    language: 'English',
    url: '/repository/articles/2024/adeyemi-soil-fertility',
    repository: true,
    abstract:
      'Three-season trial of integrated soil fertility management across Plateau, Bauchi and Nasarawa states, reporting yield and cost-benefit outcomes.',
    coverColor: C.steel,
    accessCount: 158,
  },
  {
    id: 'r-009',
    biblionumber: '102900',
    title: 'Introduction to Organic Chemistry',
    authors: ['Sarah McMurtrie'],
    type: 'book',
    subjects: ['Natural Sciences', 'Chemistry'],
    year: 2018,
    publisher: 'Pearson',
    isbn: '9781292231471',
    language: 'English',
    callNumber: 'QD251 .M36 2018',
    location: 'Main Library — Level 3, Sciences',
    copiesTotal: 12,
    copiesAvailable: 1,
    abstract:
      'Reaction mechanisms, stereochemistry and spectroscopy for first- and second-year undergraduates, with problem sets after each chapter.',
    coverColor: C.teal,
    accessCount: 604,
  },
  {
    id: 'r-010',
    title: 'JSTOR Africa Collection',
    authors: ['ITHAKA'],
    type: 'ebook',
    subjects: ['Arts & Humanities', 'Social Sciences'],
    year: 2025,
    language: 'English',
    url: 'https://www.jstor.org',
    abstract:
      'Archival journals and monographs in African history, literature and politics. Off-campus access is proxied through your university login.',
    coverColor: C.plum,
    accessCount: 489,
  },
  {
    id: 'r-011',
    biblionumber: '105330',
    title: 'Financial Accounting: A Nigerian Perspective',
    authors: ['Adaeze Okonkwo'],
    type: 'book',
    subjects: ['Management Sciences'],
    year: 2023,
    publisher: 'Longman Nigeria',
    isbn: '9789781390452',
    language: 'English',
    callNumber: 'HF5636 .O46 2023',
    location: 'Main Library — Level 2, Management',
    copiesTotal: 7,
    copiesAvailable: 4,
    abstract:
      'IFRS-aligned treatment of recognition, measurement and disclosure with illustrations from listed Nigerian entities.',
    coverColor: C.indigo,
    accessCount: 231,
  },
  {
    id: 'r-012',
    title: 'Hausa Oral Poetry and the Politics of Memory',
    authors: ['Binta Aliyu'],
    type: 'thesis',
    subjects: ['Arts & Humanities'],
    year: 2022,
    language: 'English',
    url: '/repository/theses/2022/aliyu-hausa-oral-poetry',
    repository: true,
    abstract:
      'Master’s thesis reading twentieth-century Hausa praise poetry as a contested archive of northern Nigerian political memory.',
    coverColor: C.clay,
    accessCount: 143,
  },
  {
    id: 'r-013',
    biblionumber: '104010',
    title: 'Human Anatomy and Physiology',
    authors: ['Elaine Marieb', 'Katja Hoehn'],
    type: 'book',
    subjects: ['Medicine & Health Sciences'],
    year: 2021,
    publisher: 'Pearson',
    isbn: '978013516804',
    language: 'English',
    callNumber: 'QP34.5 .M37 2021',
    location: 'Main Library — Level 2, Health Sciences',
    copiesTotal: 15,
    copiesAvailable: 0,
    abstract:
      'The standard undergraduate reference for systems anatomy and physiology, with clinical correlations and imaging plates.',
    coverColor: C.sky,
    accessCount: 812,
  },
  {
    id: 'r-014',
    title: 'Research Methods in the Social Sciences',
    authors: ['Danladi Musa'],
    type: 'ebook',
    subjects: ['Social Sciences', 'Education'],
    year: 2024,
    language: 'English',
    url: '/eresources/ebooks/musa-research-methods',
    abstract:
      'Design, sampling, instrument validity and mixed-method analysis, written around Nigerian fieldwork constraints.',
    coverColor: C.steel,
    accessCount: 355,
  },
  {
    id: 'r-015',
    biblionumber: '105501',
    title: 'Digital Signal Processing with Applications',
    authors: ['Chidi Anigbogu'],
    type: 'book',
    subjects: ['Engineering', 'Computer Science'],
    year: 2022,
    publisher: 'Heinemann Educational',
    isbn: '9789781298776',
    language: 'English',
    callNumber: 'TK5102.9 .A54 2022',
    location: 'Main Library — Level 3, Engineering',
    copiesTotal: 4,
    copiesAvailable: 2,
    abstract:
      'Sampling, transforms, filter design and DSP hardware, with MATLAB and open-source Python exercises.',
    coverColor: C.teal,
    accessCount: 176,
  },
  {
    id: 'r-016',
    title: 'Plateau State Health Survey Dataset, 2015–2024',
    authors: ['Centre for Population Studies'],
    type: 'article',
    subjects: ['Medicine & Health Sciences', 'Social Sciences'],
    year: 2025,
    language: 'English',
    url: '/repository/datasets/2025/plateau-health-survey',
    repository: true,
    abstract:
      'Open dataset and codebook covering maternal health, immunisation coverage and facility access across seventeen local government areas.',
    coverColor: C.clay,
    accessCount: 121,
  },
  {
    id: 'r-017',
    biblionumber: '103455',
    title: 'Crop Production Principles and Practice',
    authors: ['Musa Danlami'],
    type: 'book',
    subjects: ['Agriculture'],
    year: 2017,
    publisher: 'Agro Press',
    isbn: '9789782234117',
    language: 'English',
    callNumber: 'SB91 .D36 2017',
    location: 'Main Library — Level 1, Agriculture',
    copiesTotal: 9,
    copiesAvailable: 5,
    abstract:
      'Agronomy of cereals, legumes and tubers under Guinea savannah conditions, including pest and post-harvest management.',
    coverColor: C.navy,
    accessCount: 167,
  },
  {
    id: 'r-018',
    title: 'Directory of Open Access Journals (DOAJ)',
    authors: ['DOAJ'],
    type: 'journal',
    subjects: ['Natural Sciences', 'Medicine & Health Sciences', 'Engineering'],
    year: 2025,
    language: 'Multiple',
    url: 'https://doaj.org',
    abstract:
      'Index of vetted open-access journals across all disciplines — free to read on and off campus, no proxy required.',
    coverColor: C.plum,
    accessCount: 402,
  },
  {
    id: 'r-019',
    biblionumber: '105790',
    title: 'Criminology and Penal Reform in West Africa',
    authors: ['Halima Yakubu'],
    type: 'book',
    subjects: ['Law', 'Social Sciences'],
    year: 2024,
    publisher: 'Malthouse Press',
    isbn: '9789785661200',
    language: 'English',
    callNumber: 'HV7108 .Y35 2024',
    location: 'Law Library — Level 2',
    copiesTotal: 3,
    copiesAvailable: 1,
    abstract:
      'Sentencing practice, custodial conditions and restorative alternatives across Nigeria, Ghana and Senegal.',
    coverColor: C.indigo,
    accessCount: 98,
  },
  {
    id: 'r-020',
    title: 'Introductory Lectures in Mathematical Modelling (video series)',
    authors: ['Department of Mathematics'],
    type: 'av',
    subjects: ['Natural Sciences', 'Education'],
    year: 2024,
    language: 'English',
    url: '/repository/av/2024/maths-modelling',
    repository: true,
    abstract:
      'Twelve recorded lectures on ODE models in ecology and epidemiology, with downloadable problem sheets.',
    coverColor: C.steel,
    accessCount: 87,
  },
]

export const LIBRARY_HOURS: LibraryHours[] = [
  { day: 'Monday', opens: '08:00', closes: '22:00' },
  { day: 'Tuesday', opens: '08:00', closes: '22:00' },
  { day: 'Wednesday', opens: '08:00', closes: '22:00' },
  { day: 'Thursday', opens: '08:00', closes: '22:00' },
  { day: 'Friday', opens: '08:00', closes: '20:00' },
  { day: 'Saturday', opens: '10:00', closes: '18:00' },
  { day: 'Sunday', opens: '14:00', closes: '20:00' },
]

export const STUDY_SPACES: StudySpace[] = [
  {
    id: 's-01',
    name: 'Discussion Room A',
    floor: 'Level 1',
    capacity: 6,
    amenities: ['Whiteboard', 'Power outlets', 'Wi-Fi'],
    bookedSlots: ['10:00', '11:00', '15:00'],
  },
  {
    id: 's-02',
    name: 'Discussion Room B',
    floor: 'Level 1',
    capacity: 8,
    amenities: ['Screen', 'Whiteboard', 'Wi-Fi'],
    bookedSlots: ['09:00', '14:00'],
  },
  {
    id: 's-03',
    name: 'Silent Study Carrels',
    floor: 'Level 2',
    capacity: 1,
    amenities: ['Desk lamp', 'Power outlet'],
    bookedSlots: ['12:00'],
  },
  {
    id: 's-04',
    name: 'Postgraduate Research Room',
    floor: 'Level 3',
    capacity: 12,
    amenities: ['Projector', 'Air conditioning', 'Wi-Fi', 'Power outlets'],
    bookedSlots: ['08:00', '09:00', '16:00', '17:00'],
  },
  {
    id: 's-05',
    name: 'Digital Commons Pods',
    floor: 'Level 2',
    capacity: 4,
    amenities: ['Workstations', 'Scanner', 'Wi-Fi'],
    bookedSlots: ['13:00'],
  },
]

export const BOOKING_SLOTS = [
  '08:00',
  '09:00',
  '10:00',
  '11:00',
  '12:00',
  '13:00',
  '14:00',
  '15:00',
  '16:00',
  '17:00',
]

export const FAQS: FaqEntry[] = [
  {
    question: 'How many items can I borrow at once?',
    answer:
      'Undergraduates may hold 4 items for 14 days, postgraduates 8 items for 21 days, and faculty 12 items for 30 days. Reference and reserve items are consultation-only.',
  },
  {
    question: 'How do I read e-resources from off campus?',
    answer:
      'Open any electronic resource from inside REACH while signed in. The app passes your university credentials to the library proxy, so subscribed databases recognise you without a separate login.',
  },
  {
    question: 'What happens if I return an item late?',
    answer:
      'Overdue items accrue a daily fine and block further borrowing until settled. REACH sends a reminder three days before an item is due and again on the due date.',
  },
  {
    question: 'How is XP calculated?',
    answer:
      'Browsing the catalogue earns 5 XP, opening an e-resource 10 XP, downloading 20 XP, reserving a book 30 XP and borrowing a physical book 50 XP. Daily caps apply to the repeatable actions so XP tracks real engagement.',
  },
  {
    question: 'Who can see my reading activity?',
    answer:
      'Nobody, unless you opt in. Activity sharing is off by default; when enabled, your reads contribute to de-identified departmental trends only — never a named feed.',
  },
  {
    question: 'Can I use REACH without a network connection?',
    answer:
      'Yes. Your loans, saved records and recently viewed items stay readable offline, and actions such as renewals queue locally and sync as soon as you reconnect.',
  },
  {
    question: 'How do I request help from a librarian?',
    answer:
      'Use Library tools → Ask a librarian. Subject librarians respond within one working day and can meet you in person, over video, or by email.',
  },
]

export const FOLLOW_SUGGESTIONS: FollowedUser[] = [
  { id: 'u-201', name: 'Dr. Naomi Bitrus', department: 'Public Health', role: 'faculty', level: 11, avatarInitials: 'NB' },
  { id: 'u-202', name: 'Suleiman Abdulkadir', department: 'Law', role: 'postgraduate', level: 8, avatarInitials: 'SA' },
  { id: 'u-203', name: 'Chinaza Eze', department: 'Civil Engineering', role: 'undergraduate', level: 5, avatarInitials: 'CE' },
  { id: 'u-204', name: 'Prof. Yakubu Dung', department: 'Agronomy', role: 'faculty', level: 13, avatarInitials: 'YD' },
  { id: 'u-205', name: 'Mercy Longtau', department: 'Education', role: 'postgraduate', level: 7, avatarInitials: 'ML' },
]

export const FEED_SEED: Omit<FeedItem, 'at'>[] = [
  { id: 'f-1', cohort: 'A postgraduate in Medicine', action: 'borrowed', resourceTitle: 'Human Anatomy and Physiology', resourceId: 'r-013' },
  { id: 'f-2', cohort: 'A reader in Law', action: 'reserved', resourceTitle: 'Nigerian Constitutional Law: Cases and Commentary', resourceId: 'r-002' },
  { id: 'f-3', cohort: 'An undergraduate in Sciences', action: 'downloaded', resourceTitle: 'Journal of Applied Sciences and Environmental Management', resourceId: 'r-003' },
  { id: 'f-4', cohort: 'A researcher in Environmental Sciences', action: 'opened', resourceTitle: 'Tin Mining and Land Degradation on the Jos Plateau', resourceId: 'r-004' },
  { id: 'f-5', cohort: 'A reader in Management Sciences', action: 'borrowed', resourceTitle: 'Financial Accounting: A Nigerian Perspective', resourceId: 'r-011' },
  { id: 'f-6', cohort: 'An undergraduate in Education', action: 'opened', resourceTitle: 'Research Methods in the Social Sciences', resourceId: 'r-014' },
]

export const ANNOUNCEMENTS = [
  {
    title: 'Extended hours for first-semester examinations',
    body: 'The Main Library stays open until midnight from 18 to 30 August. Level 2 and the Digital Commons remain staffed throughout.',
  },
  {
    title: 'New: Plateau health survey dataset in the repository',
    body: 'Ten years of survey microdata and the accompanying codebook are now open for download from the institutional repository.',
  },
  {
    title: 'Workshop — systematic literature searching',
    body: 'A hands-on session for postgraduates on Boolean searching, citation chaining and reference management. Thursday, 14:00, Digital Commons.',
  },
]
